### ISSUE TITLE
Nondeterministic `convertToString`

### ISSUE THREAD

**Issue by tjbai** [tjbai/p2c#17]
I've had a couple of `codegen` tests failing for a while now so I did some digging. Not sure if I'm missing something or if this is a result of some kind of mutation?

If you load into utop and run the following command twice in a row, you get a different result both times.
```
ConModule.convertToString
       [
         Expression
           (Assignment
              { name = "a"; value = IntLiteral 5; t = Ast.Int; operator = None });
       ];;
```

First time:
```
string = "int a = 5;\n"
```

Second time:
```
string = "a = 5;\n"
```

**Comment by tjbai** [comment]
This happens pretty consistently with other cases, it looks like the type def gets cut off if you call `ConModule.convertToString` multiple times?

**Comment by semperExploro** [comment]
If you run multiple lines with the same variable under a parent test then it counts it as a single scope. 

E.g. 

Int a = 5; //result from one test 

Int a = 8; //subsequent test ->  won't work cause previous line already declared it. Needs to be a = 8

**Comment by tjbai** [comment]
this makes sense. the main thing i'm worried about is that the behavior seems to be a little unpredictable? i didn't change anything and it's now just magically passing without an issue hmm

**Comment by semperExploro** [comment]
I think I did `dune clean` and then `dune test`. If you do `dune test` without `dune clean` I think memory still persists. Shouldn't be an issue for the application, as far as I can tell.

**Comment by tjbai** [comment]
Yeah it looks everything works after a `dune clean`.
