### ISSUE TITLE
Codegen operator precedence

### ISSUE THREAD

**Issue by tjbai** [tjbai/p2c#20]
Not sure how difficult it would be to address this, so probably not super high priority:

`2+3 and 3+4` and `2+(3 and 3+4)` generate different ASTs because of operator precedence:

```sexp
((Function (name main) (parameters ()) (return Int)
  (body
   ((Expression
     (BinaryOp (operator And)
      (left
       (BinaryOp (operator Add) (left (IntLiteral 2)) (right (IntLiteral 3))))
      (right
       (BinaryOp (operator Add) (left (IntLiteral 3)) (right (IntLiteral 4))))))))))
```

```sexp
((Function (name main) (parameters ()) (return Int)
  (body
   ((Expression
     (BinaryOp (operator Add) (left (IntLiteral 2))
      (right
       (BinaryOp (operator And) (left (IntLiteral 3))
        (right
         (BinaryOp (operator Add) (left (IntLiteral 3))
          (right (IntLiteral 4))))))))))))
```

However, both of these ASTs result in the following C output:

```
2 + 3 && 3 + 4;
```

To properly handle this, the `codegen` module would need to insert parentheses when implicit operator precedence is violated.

**Comment by tjbai** [comment]
A simple solution would be to _always_ insert parentheses around `binaryOps`. 

So `2+3+4` in python would result in something like `(2+(3+4))` in C. We could just leave it that way (say it's a feature) OR have some post-processing codegen step that removes extraneous parentheses. Just an idea.

**Comment by semperExploro** [comment]
Resolved
