### ISSUE TITLE
Codegen scoping

### ISSUE THREAD

**Issue by tjbai** [tjbai/p2c#22]
This is a hard case with scoping, but I think there might be a simple (hacky) solution?

Consider:

```python
def foo():
    i = 0
    for x in range(10):
        i += x

i = 0
print(i)
```

This generates:
```c
 foo(){
	int i = 0;
	for(int x=0;x<=10;x+=1){
		i + x;
	}
}
int main(){
	i = 0;
	printf("", i);
}
```

Ignoring the missing `void` (see the other issue), the `i` in `main` should be a declaration. Although this is difficult to handle in general, a simple solution for this specific example might just be to clear the lookup table everytime we enter a new function?

**Comment by tjbai** [comment]
Also, I just noticed that `printf` is missing the `%d` placeholder as well?

**Comment by semperExploro** [comment]
Resolved
