### ISSUE TITLE
`printf`

### ISSUE THREAD

**Issue by tjbai** [tjbai/p2c#24]
```python
i = 0
print(i)
```

goes to
```c
int i = 0;
printf("", i);
```

I'm honestly not sure what happens here because it seems like it should be covered here:

```ocaml
 let getReturnType tree_main expList =
    let rec helper expList acc =
      match expList with
      | [] -> acc
      | hd :: tl -> (
          match hd with
          | Ast.IntLiteral _ -> helper tl (acc ^ "%d ")
          | Ast.StringLiteral _ -> helper tl (acc ^ "%s ")
          | Ast.BooleanLiteral _ -> helper tl (acc ^ "%d ")
          | Ast.FunctionCall { name = id; arguments = _ } -> (
              match FunctionLookUp.findReturnType id tree_main with
              | Ast.Int -> helper tl (acc ^ "%d ")
              | Ast.String -> helper tl (acc ^ "%s ")
              | Ast.Boolean -> helper tl (acc ^ "%d ")
              | _ -> failwith "Invalid type")
          | _ -> helper tl acc)
    in
    helper expList ""
```

**Comment by semperExploro** [comment]
Will address (and hopefully fix), all issues tonight.

**Comment by tjbai** [comment]
I changed some tests in `endtoendtests` that should fail for now but hopefully pass when all the small bugs are fixed. After going through a ton of other examples using the REPL, I didn't really find anything else so that's good 😃

**Comment by semperExploro** [comment]
All the tests work - (although Idk why but we're encountering some memory issues so sometimes one or two tests fail, other times it doesn't...), but I verified by printing the outcome out. 

All issues should be addressed.
