### ISSUE TITLE
Create new hashtable each time `convertToString` is called

### ISSUE THREAD

**Issue by tjbai** [tjbai/p2c#27]
A possible solve for the testing issue is this small refactor—rather than maintaining a global lookup instance in `Codegenutil.Common`, initiate a new hashtable each time `convertToString` is called OR nuke the hashtable each time. I'm not sure if there is anything that is _supposed_ to be persisted between calls to `convertToString`? If so, we can talk about solutions because having global side effects like that probably isn't super ideal.

As an example in `parse.ml` I init a new table each time `to_ast` is called:
```ocaml
(* string -> processed ast *)
let to_ast (s : string) : ast =
  let raw_ast = to_raw_ast s in
  raw_ast
  |> map_expressions ~f:replace_neg ~deep:true
  |> map_expressions ~f:(infer_type ~tbl:(init_tbl raw_ast)) ~deep:false
  |> gather_main
```

**Comment by semperExploro** [comment]
Fixed - rearranged the tests which solved the issue (Problem hidden)
