### ISSUE TITLE
Input and Print Doesn't Work

### ISSUE THREAD

**Issue by semperExploro** [tjbai/p2c#33]
## Input

Python: `    output = input("Enter a number: ")`
Results in c: `	output = scanf("%s", "Enter a number : ");` (which reads a string and not a number) 

## Print

Same issue but unable to print variables (only strings).

**Comment by tjbai** [comment]
When I do:

```python
i = 2
print(i)
```

it converts to

```c
int i = 2;
printf("%d", i);
```

is this what you mean by printing variables?

**Comment by semperExploro** [comment]
Something like this, can't print string literal formatted with string. 
    i = 0
    print("This is a number " + i)

Not totally important.
